### PR TITLE
[rapids] Test dask rapids

### PR DESCRIPTION
**Pull request by cjac**
custom_image_utils/shell_script_generator.py
* added retry function
* reduced debug output when -x is passed
* reducing buffer for write to startup-script.log

examples/secure-boot/README.md
* re-named the docker images for clarity

examples/secure-boot/build-current-images.sh
* using the same timestamp for all images
* added perl code to disk_usage to extract maximum disk usage during installation
* making request for image and instance list once here instead of each
  time an image is about to be created

examples/secure-boot/install_gpu_driver.sh
* add is_debuntu to simplify common is_debian || is_ubuntu use case
* prepend clean to execute_with_retries to reduce maximum image size
* downloading assets to ram disk to reduce maximum image size
* added sync to key points of the script to allow accurate measurement
  of maximum disk usage
* moved initialization steps to new function prepare_to_install
* created exit_handler function which gets executed before script exits

examples/secure-boot/pre-init.screenrc
* re-ordered versions alphabetically

examples/secure-boot/pre-init.sh
* default to using standalone dask runtime because yarn is getting outdated
* re-using cache of image and instance list from parent script
* increased machine type to accommodate ram disk
* updated disk image sizes based on disk usage analysis
* dask image is no longer intermediate

examples/secure-boot/dask.sh
examples/secure-boot/rapids.sh
* refactored these scripts to be nearly identical
* removed spark-related logic (see spark-rapids)
* remove dask packages if they were installed
* moved initialization steps to new function prepare_to_install
* created exit_handler function which gets executed before script exits

### CODE REVIEW

**Comment by cjac** [comment]
@tomasanda 
@igor-susic

Can you please test these changes and let me know if I'm good to merge them into main?

**Comment by igor-susic** [comment]
After testing with:

````shell
git clone https://github.com/cjac/custom-images.git custom-images
Cloning into 'custom-images'...
+ cd custom-images
+ git checkout test-dask-rapids-20241021
````

Still the same issue persists:
````shell
/tmp/tmpxnmzbctc: line 144: num_src_certs: unbound variable
````

**Comment by cjac** [comment]
Thanks for the report, Igor!  Hopefully this will address that problem.

**Comment by tomasanda** [comment]
Thank you @cjac 👍

**Pull request merged**
